export interface Sinister {
  _id: string,
  client_id: string,
  vehicle_id: string,
  observations: string,
  estado_de_aprobacion:string,
  policy_id:string,
  monto:number,
  code: number,
  date: string,
  created_at: Date,
  updated_at: Date,
  receipt_id: string,
  receipt_code: number,
  fechaIni: string,
  fechaFin: string,
  policy_code: number,
  image_url: any,
}
